# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - refs/heads/master
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job
  pool:
    name: Default
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: '**/DBManageSystem.ManageWebAPI.csproj'
      arguments: -o $(Build.ArtifactStagingDirectory)/Output
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/Output
